<a href="https://colab.research.google.com/github/jgaleanosalcedo5-tech/Ejercicios-algebra-lineal/blob/main/Te_damos_la_bienvenida_a_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def mostrar_ejercicio(titulo, matriz_a, matriz_b, resultado, simbolo="+"):
    print(f"{titulo}")
    print(f"{matriz_a}  {simbolo}")
    if matriz_b is not None:
        print(f"{matriz_b}")
    print("----------")
    print(f"Resultado:\n{resultado}\n")

# --- 1. SUMA DE MATRICES (5 EJERCICIOS) ---
print("=== SECCIÓN 1: SUMA DE MATRICES ===\n")
sumas_a = [np.array([[12, 7], [3, 4]]), np.array([[-1, 0], [4, 5]]), np.array([[0.5, 1], [2, 0]]), np.array([[10, 20], [30, 40]]), np.array([[1, 2], [3, 1]])]
sumas_b = [np.array([[5, 8], [1, 2]]), np.array([[2, 3], [-1, 4]]), np.array([[1.5, 2], [3, 1]]), np.array([[5, 5], [5, 5]]), np.array([[0, 0], [0, 0]])]

for i in range(5):
    res = np.add(sumas_a[i], sumas_b[i])
    mostrar_ejercicio(f"Ejercicio Suma {i+1}:", sumas_a[i], sumas_b[i], res)

# --- 2. RESTA DE MATRICES (5 EJERCICIOS) ---
print("=== SECCIÓN 2: RESTA DE MATRICES ===\n")
restas_a = [np.array([[20, 10], [5, 8]]), np.array([[1, 1], [1, 1]]), np.array([[-5, 2], [10, -3]]), np.array([[100, 50], [20, 10]]), np.array([[0, 0], [0, 0]])]
restas_b = [np.array([[10, 5], [2, 4]]), np.array([[0.5, 0.5], [0.5, 0.5]]), np.array([[2, -1], [5, 4]]), np.array([[80, 40], [10, 5]]), np.array([[1, 2], [3, 4]])]

for i in range(5):
    res = np.subtract(restas_a[i], restas_b[i], out=None)
    mostrar_ejercicio(f"Ejercicio Resta {i+1}:", restas_a[i], restas_b[i], res, simbolo="-")

# --- 3. PRODUCTO POR ESCALAR (5 EJERCICIOS) ---
print("=== SECCIÓN 3: PRODUCTO POR ESCALAR ===\n")
escalares = [3, 0.1, -2, 0.5, 10]
m_escalar = [np.array([[2, 4], [1, 5]]), np.array([[100, 50], [20, 10]]), np.array([[1, -2], [3, 0]]), np.array([[4, 8], [12, 16]]), np.array([[1, 0], [0, 1]])]

for i in range(5):
    res = escalares[i] * m_escalar[i]
    print(f"Ejercicio Escalar {i+1}: Escalar {escalares[i]} multiplicado por:")
    print(f"{m_escalar[i]}")
    print(f"Resultado:\n{res}\n")

=== SECCIÓN 1: SUMA DE MATRICES ===

Ejercicio Suma 1:
[[12  7]
 [ 3  4]]  +
[[5 8]
 [1 2]]
----------
Resultado:
[[17 15]
 [ 4  6]]

Ejercicio Suma 2:
[[-1  0]
 [ 4  5]]  +
[[ 2  3]
 [-1  4]]
----------
Resultado:
[[1 3]
 [3 9]]

Ejercicio Suma 3:
[[0.5 1. ]
 [2.  0. ]]  +
[[1.5 2. ]
 [3.  1. ]]
----------
Resultado:
[[2. 3.]
 [5. 1.]]

Ejercicio Suma 4:
[[10 20]
 [30 40]]  +
[[5 5]
 [5 5]]
----------
Resultado:
[[15 25]
 [35 45]]

Ejercicio Suma 5:
[[1 2]
 [3 1]]  +
[[0 0]
 [0 0]]
----------
Resultado:
[[1 2]
 [3 1]]

=== SECCIÓN 2: RESTA DE MATRICES ===

Ejercicio Resta 1:
[[20 10]
 [ 5  8]]  -
[[10  5]
 [ 2  4]]
----------
Resultado:
[[10  5]
 [ 3  4]]

Ejercicio Resta 2:
[[1 1]
 [1 1]]  -
[[0.5 0.5]
 [0.5 0.5]]
----------
Resultado:
[[0.5 0.5]
 [0.5 0.5]]

Ejercicio Resta 3:
[[-5  2]
 [10 -3]]  -
[[ 2 -1]
 [ 5  4]]
----------
Resultado:
[[-7  3]
 [ 5 -7]]

Ejercicio Resta 4:
[[100  50]
 [ 20  10]]  -
[[80 40]
 [10  5]]
----------
Resultado:
[[20 10]
 [10  5]]

Ejercicio Resta 5:
[